### ISSUE TITLE
执行getweight.py这个脚本处理yolov5s.pt的时候报错 No module named 'models'？

### ISSUE THREAD

**Issue by zhaoxiaolong2020** [wdhao/tensorrtCV#11]
我执行getweight.py脚本的时候报错， 只保存为.pth

```
if __name__ == '__main__':

    #!将yolo5s.pt文件保存为yolov5s.pth文件
    model = torch.load(path + 'yolov5s.pt')['model'].float()
    torch.save(model.state_dict(), path + 'yolov5s.pth')  #只保存模型权重参数，不保存模型结构
```
报错如下
```
(py38torch190-smoke) zxl@R9000P:~/mywork/tensorrtCV$ python getWeights_new.py
Traceback (most recent call last):
  File "getWeights_new.py", line 67, in <module>
    model = torch.load(path + 'yolov5s.pt')['model'].float()
  File "/home/zxl/miniconda3/envs/py38torch190-smoke/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/zxl/miniconda3/envs/py38torch190-smoke/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/zxl/miniconda3/envs/py38torch190-smoke/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'
```
这是什么原因呢？ 我把下载下来的yolov5s.pt放在了model文件夹下，脚本的路径也对应修改了。

**Comment by SixGodGG** [comment]
getweight.py 放在model 同级别文件夹中了么？

**Comment by zhaoxiaolong2020** [comment]
> getweight.py 放在model 同级别文件夹中了么？

问题已经解决要放到yolov5的文件目录下才可以
